replicaCount: 1
image:
  repository: harbor.e-mothep.com/keyopssys/quote-app-back
  pullPolicy: IfNotPresent
  tag: 0.5.6
imagePullSecrets:
  - name: regcred
nameOverride: quote-back
fullnameOverride: keyopssys-quote-back
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8081
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: quote-back.e-mothep.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: 8081
readinessProbe:
  httpGet:
    path: /
    port: 8081
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
postgresql:
  enabled: true
  primary:
    persistence:
      size: 2Gi
  global:
    postgresql:
      auth:
        postgresPassword: manage
        password: devisPwd
        username: pgDevis
        database: devis_db
    storageClass: standard
quote:
  config:
    version: v1
    geoloc:
      uri: https://${quote.config.geoloc.base-url}/search/${quote.config.geoloc.version-number}/reverseGeocode/${quote.config.geoloc.position}.${quote.config.geoloc.ext}?key=${quote.config.geoloc.key}
      baseUrl: api.tomtom.com
      versionNumber: 2
      position: '%s,%s'
      ext: json
      key: c5vqmn4AVk4kcaFBu0bXQV9f8M6YGGQ8
    legalinfo:
      uri: https://${quote.config.legalinfo.base-url}/${quote.config.legalinfo.version}/suggestions?q=%s&longueur=%s
      baseUrl: api.pappers.fr
      version: v2
    security:
      filterChain:
        login: /oauth2/**
        api: /api/**
  server:
    port: 8081
  logging:
    level:
      org: INFO
  spring:
    flyway:
      schemas:
        - devis
      locations:
        - classpath:db/migration
    jooq:
      sql-dialect: postgres
    application:
      name: backend
    datasource:
      url: jdbc:postgresql://back-postgresql.quote.svc.cluster.local:5432/devis_db
      username: pgDevis
      password: devisPwd
    mail:
      host: ssl0.ovh.net
      port: 587
      username: no-reply@keyopssys.com
      password: P*7@FCGul"CrHRJ`iDA/
      properties:
        mail:
          protocol: smtp
          tls: true
          smtp:
            auth: true
            starttls:
              enable: true
    security:
      oauth2:
        client:
          registration:
            keycloak:
              clientId: gds-test
              clientSecret: saOTA3vb2a2Pwr4iN20HHlaqZ5DbbC7e
          provider:
            keycloak:
              authorizationUri: https://login.keyopssys.com/realms/dev/protocol/openid-connect/auth
              tokenUri: https://login.keyopssys.com/realms/dev/protocol/openid-connect/token
              userInfoUri: https://login.keyopssys.com/realms/dev/protocol/openid-connect/userinfo
              issuerUri: https://login.keyopssys.com/realms/dev
              jwkSetUri: https://login.keyopssys.com/realms/dev/protocol/openid-connect/certs
              userNameAttribute: sub
        resourceserver:
          jwt:
            issuerUri: https://login.keyopssys.com/realms/dev
            jwkSetUri: https://login.keyopssys.com/realms/dev/protocol/openid-connect/certs
env:
  SPRING_CONFIG_LOCATION: /config/application.yaml
