replicaCount: 1
image:
  repository: harbor.e-mothep.com/keyopssys/quote-app-front
  pullPolicy: IfNotPresent
  tag: 0.14.4
imagePullSecrets:
  - name: regcred
nameOverride: quote-front
fullnameOverride: keyopssys-quote-front
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: rec-quote.keyopssys.e-mothep.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: rec-quote.keyopssys.e-mothep.local-tls
      hosts:
        - rec-quote.keyopssys.e-mothep.local
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
quote:
  enabled: false
  host: keyopssys-quote-back.quote.svc.cluster.local
  port: 8081
