name: Update Helm Charts
on:
  repository_dispatch:
    types: [Integration-with-Automation]
jobs:
  update-chart:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'charts/${{ github.event.client_payload.app }}/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ github.event.client_payload.version }}
          branch: deployment/${{ github.event.client_payload.app }}-${{ github.event.client_payload.version }}
          targetBranch: development
          createPR: true
          message: 'Update ${{ github.event.client_payload.app }} Image Version to ${{ steps.image.outputs.version }}' 
